### ISSUE TITLE
hspec-core-2.9.3 fails to build for ghcjs

### ISSUE THREAD

**Issue by harendra-kumar** [hspec/hspec#599]
[This](https://app.circleci.com/pipelines/github/composewell/streamly/3417/workflows/08859c5f-d2a8-419d-a095-2c1c2cd17711/jobs/15549) is the failure build.

```
[11 of 40] Compiling Test.Hspec.Core.Formatters.Pretty.Parser ( src/Test/Hspec/Core/Formatters/Pretty/Parser.hs, dist/build/Test/Hspec/Core/Formatters/Pretty/Parser.js_o )

src/Test/Hspec/Core/Formatters/Pretty/Parser.hs:54:1: error:
    Could not find module ‘Lexer’
    Use -v to see a list of the files searched for.
   |
54 | import           Lexer
   | ^^^^^^^^^^^^^^^^^^^^^^

src/Test/Hspec/Core/Formatters/Pretty/Parser.hs:55:1: error:
    Could not find module ‘Parser’
    Use -v to see a list of the files searched for.
   |
55 | import qualified Parser as GHC
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Test/Hspec/Core/Formatters/Pretty/Parser.hs:56:1: error:
    Could not find module ‘StringBuffer’
    Use -v to see a list of the files searched for.
   |
56 | import           StringBuffer
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...

cabal: Failed to build hspec-core-2.9.3 (which is required by hspec-2.9.3)
```

Looks like this is due to the ghc dependency introduced by https://github.com/hspec/hspec/commit/0e9ad052be14c639e7981958524b952906b3ae8a . We can possibly avoid pretty printing on ghcjs if it cannot be made to work.

**Comment by sol** [comment]
@harendra-kumar thanks for reporting this.  #600 is a tentative solution.

One thing that puzzles me is that apparently ghcjs provides the `ghc` package, but with a different API?  If `ghc` would not be available in the first place we could use an "automatic" cabal flag to detect this, which might be more robust.

In addition, will this be an issue with cross-compilation in general?  Say, is `ghc` available when cross-compiling (@angerman, any thoughts)?

**Comment by sol** [comment]
I'm going to release #599 as `2.9.4`.  I'm still not very satisfy for three reasons:

- I don't understand what exactly the `ghc` package provides for GHCJS
- I don't have a test setup, ideally we would have CI for GHCJS
- I don't know what the situation is with the `ghc` package and cross-compilation in general (+ I don't have a test setup to try)

Any input is still very much appreciated.
