### ISSUE TITLE
hspec-meta doesn't work with HUnit-1.4

### ISSUE THREAD

**Issue by phadej** [hspec/hspec#281]
The issue tracker points here, but cannot see the package inside this repository. Is it somehow assembled from this, it fails at:

```
    [ 6 of 25] Compiling Test.Hspec.Core.Example ( hspec-core/src/Test/Hspec/Core/Example.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Test/Hspec/Core/Example.o )
    
    .../src/Test/Hspec/Core/Example.hs:92:15:
        Not in scope: data constructor ‘HUnit.Location’
```

**Comment by sol** [comment]
This is fixed

**Comment by sol** [comment]
Regarding your question, check the README.
