### ISSUE TITLE
Build error with ghc 8.6.1

### ISSUE THREAD

**Issue by peti** [hspec/hspec#378]
hspec-core-2.5.6 does not seem to compile with ghc-8.6.1:

~~~
test/Test/Hspec/Core/Example/LocationSpec.hs:29:15: error:
    • No instance for (Control.Monad.Fail.MonadFail (Either ()))
        arising from a do statement
        with the failable pattern ‘23’
    • In a stmt of a 'do' block: 23 <- Right (42 :: Int)
      In the expression:
        do 23 <- Right (42 :: Int)
           return ()
      In an equation for ‘foo’:
          foo
            = do 23 <- Right (42 :: Int)
                 return ()
   |
29 |               23 <- Right (42 :: Int)
   |               ^^^^^^^^^^^^^^^^^^^^^^^
~~~

**Comment by sol** [comment]
Fixed on Hackage. Thanks.
