### ISSUE TITLE
hspec-core <= 2.9.2 do not build with GHC 9.4

### ISSUE THREAD

**Issue by andreasabel** [hspec/hspec#677]
The type of `fork#` changed in GHC 9.4, see https://gitlab.haskell.org/ghc/ghc/-/issues/19992#note_360634.
Consequently, some old versions of hspec-core fail to build with GHC 9.4.  I think all <= 2.9.2 should have `base < 4.17` to prevent them being selected for build plans with GHC 9.4.

E.g. 2.9.1:
```
Building library for hspec-core-2.9.1..
[ 1 of 37] Compiling Control.Concurrent.Async ( vendor/Control/Concurrent/Async.hs, dist/build/Control/Concurrent/Async.o, dist/build/Control/Concurrent/Async.dyn_o )

vendor/Control/Concurrent/Async.hs:865:16: error:
    • Couldn't match expected type: State# RealWorld
                                    -> (# State# RealWorld, a1 #)
                  with actual type: IO ()
    • In the first argument of ‘fork#’, namely ‘action’
      In the expression: fork# action s
      In the expression:
        case (fork# action s) of (# s1, tid #) -> (# s1, ThreadId tid #)
    |
865 |    case (fork# action s) of (# s1, tid #) -> (# s1, ThreadId tid #)
    |                ^^^^^^

vendor/Control/Concurrent/Async.hs:870:22: error:
    • Couldn't match expected type: State# RealWorld
                                    -> (# State# RealWorld, a0 #)
                  with actual type: IO ()
    • In the second argument of ‘forkOn#’, namely ‘action’
      In the expression: forkOn# cpu action s
      In the expression:
        case (forkOn# cpu action s) of
          (# s1, tid #) -> (# s1, ThreadId tid #)
    |
870 |    case (forkOn# cpu action s) of (# s1, tid #) -> (# s1, ThreadId tid #)
    |                      ^^^^^^
```

**Comment by andreasabel** [comment]
Fixed by Hackage revisions bounding `base` by `<4.17` for `hspec-core >= 2.4.6 && <= 2.9.2`.
